config/routes.rb
Rails.application.routes.draw do
  resources :transportations
  resources :locations
  resources :destinations
  resources :categories
  resources :foods

  root 'categories#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :food_categories
    has_many :foods, through: :food_categories
    has_many :dest_categories
    has_many :destinations, through: :dest_categories
    has_many :trans_categories
    has_many :transporations, through: :trans_categories

    validates :category, presence: true, uniqueness: true
end

app/models/dest_category.rb
class DestCategory < ApplicationRecord
    belongs_to :destination
    belongs_to :category

    validates :category_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_like.rb
class DestLike < ApplicationRecord
    belongs_to :destination
    belongs_to :like 

    validates :like_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_location.rb
class DestLocation < ApplicationRecord
    belongs_to :destination
    belongs_to :location 

    validates :location_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_note.rb
class DestNote < ApplicationRecord
    belongs_to :destination
    belongs_to :note

    validates :note_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_special.rb
class DestSpecial < ApplicationRecord
    belongs_to :destination
    belongs_to :special

    validates :special_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/destination.rb
class Destination < ApplicationRecord
    has_many :dest_categories
    has_many :dest_locations
    has_many :dest_notes
    has_many :dest_recommendations
    has_many :dest_specials
    has_many :dest_likes

    has_many :categories, through: :dest_categories
    has_many :locations, through: :dest_locations
    has_many :notes, through: :dest_notes
    has_many :recommendations, through: :dest_recommendations
    has_many :specials, through: :dest_specials
    has_many :likes, through: :dest_likes

    validates :name, presence: true, uniqueness: true
end

app/models/food.rb
class Food < ApplicationRecord
    has_many :food_categories
    has_many :food_locations
    has_many :food_notes
    has_many :food_recommendations
    has_many :food_specials
    has_many :food_likes

    has_many :categories, through: :food_categories
    has_many :locations, through: :food_locations
    has_many :notes, through: :food_notes
    has_many :recommendations, through: :food_recommendations
    has_many :specials, through: :food_specials
    has_many :likes, through: :food_likes

    validates :name, presence: true, uniqueness: true
end

app/models/food_like.rb
class FoodLike < ApplicationRecord
    belongs_to :food
    belongs_to :like

    validates :like_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/food_note.rb
class FoodNote < ApplicationRecord
    belongs_to :food 
    belongs_to :note 

    validates :note_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/food_special.rb
class FoodSpecial < ApplicationRecord
    belongs_to :food 
    belongs_to :special 

    validates :special_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/like.rb
class Like < ApplicationRecord
    has_many :food_likes
    has_many :foods, through: :food_likes
    has_many :dest_likes
    has_many :destinations, through: :dest_likes
    has_many :trans_likes
    has_many :transporations, through: :trans_likes

    validates :info, presence: true, uniqueness: true
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :food_locations
    has_many :foods, through: :food_locations
    has_many :dest_locations
    has_many :destinations, through: :dest_locations
    has_many :trans_locations
    has_many :transporations, through: :trans_locations

    validates :location, presence: true, uniqueness: true
end

app/models/note.rb
class Note < ApplicationRecord
    has_many :food_notes
    has_many :foods, through: :food_notes
    has_many :dest_notes
    has_many :destinations, through: :dest_notes
    has_many :trans_notes
    has_many :transporations, through: :trans_notes

    validates :info, presence: true, uniqueness: true
end

app/models/special.rb
class Special < ApplicationRecord
    has_many :food_specials
    has_many :foods, through: :food_specials
    has_many :dest_specials
    has_many :destinations, through: :dest_specials

    validates :info, presence: true, uniqueness: true
end

app/models/trans_like.rb
class TransLike < ApplicationRecord
    belongs_to :transportation 
    belongs_to :like

    validates :like_id, presence: true, uniqueness: { scope: :transportation_id }
end

app/models/trans_note.rb
class TransNote < ApplicationRecord
    belongs_to :transportation 
    belongs_to :note

    validates :note_id, presence: true, uniqueness: { scope: :transportation_id }
end

app/models/transportation.rb
class Transportation < ApplicationRecord
    has_many :trans_categories
    has_many :trans_locations
    has_many :trans_notes
    has_many :trans_likes

    has_many :categories, through: :trans_categories
    has_many :locations, through: :trans_locations
    has_many :notes, through: :trans_notes
    has_many :likes, through: :trans_likes

    validates :name, presence: true, uniqueness: true
end

app/controllers/transportations_controller.rb
class TransportationsController < ApplicationController
  before_action :set_transportation, only: %i[ show edit update destroy ]

  # GET /transportations or /transportations.json
  def index
    @transportations = Transportation.all.sort { |a, b| a[:name] <=> b[:name] }
  end

  # GET /transportations/1 or /transportations/1.json
  def show

    
    @transnotes = TransNote.where(transportation_id: params[:id]).to_a
    
    if @transnotes != []
      @notes = []
      @transnotes.each do |n|
        @notes.push(Note.find_by(:id => n[:note_id]))
      end
    end
  
    @translikes = TransLike.where(transportation_id: params[:id]).to_a
    
    if @translikes != []
      @likes = []
      @translikes.each do |l|
        @likes.push(Like.find_by(:id => l[:like_id]))
      end
    end
  end

  # GET /transportations/new
  def new
    @transportation = Transportation.new
  end

  # GET /transportations/1/edit
  def edit
  end

  # POST /transportations or /transportations.json
  def create
    @transportation = Transportation.new(transportation_params)

    respond_to do |format|
      if @transportation.save
        format.html { redirect_to @transportation, notice: "Transportation was successfully created." }
        format.json { render :show, status: :created, location: @transportation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transportations/1 or /transportations/1.json
  def update
    respond_to do |format|
      if @transportation.update(transportation_params)
        format.html { redirect_to @transportation, notice: "Transportation was successfully updated." }
        format.json { render :show, status: :ok, location: @transportation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transportations/1 or /transportations/1.json
  def destroy
    @transportation.destroy
    respond_to do |format|
      format.html { redirect_to transportations_url, notice: "Transportation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transportation
      @transportation = Transportation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transportation_params
      params.require(:transportation).permit(:name, :hours, :website)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/views/transportations/_form.html.erb
<%= form_with(model: transportation) do |form| %>
  <% if transportation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transportation.errors.count, "error") %> prohibited this transportation from being saved:</h2>

      <ul>
        <% transportation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.text_field :hours %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transportations/edit.html.erb
<h1>Editing Transportation</h1>

<%= render 'form', transportation: @transportation %>

<%= link_to 'Show', @transportation %> |
<%= link_to 'Back', transportations_path %>

app/views/transportations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transportations</h1>

<table>
  <thead>
    <tr>
      <th class='name'>Name</th>
      <th class='hours'>Hours</th>
      <th class='web'>Website</th>
    </tr>
  </thead>

  <tbody>
    <% @transportations.each do |transportation| %>
      <tr>
        <td><%= link_to transportation.name, transportation %></td>
        <td><% transportation.hours.split(',').each do |hour|%>
              <%= hour %></br>
            <% end %></td>
        <td><a href='<%= transportation.website %>'><%= transportation.website %></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br/>

<%= link_to "Food", foods_path %>
<%= link_to "Destinations", destinations_path %>

</br>
<%= link_to "Categories", categories_path %>
<%= link_to "Locations", locations_path %>

app/views/transportations/new.html.erb
<h1>New Transportation</h1>

<%= render 'form', transportation: @transportation %>

<%= link_to 'Back', transportations_path %>

app/views/transportations/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  
  <%= @transportation.name %>
</h2>

<p>
  <strong>Hours:</strong>
  <br/>
  <ul>
  <%@transportation.hours.split(/[,]/).each do |hour|%>
    <li><%= hour %></li><br/>
  <%end%>
  </ul>
</p>

<% if @notes %>
<p>
  <strong>Notes:</strong><br/>
  <ul>
    <%@notes.each do |note|%>
      <% note.info.split(/[;]/).each do |n| %>
        <li><%= n %></li><br/>
      <% end %>
    <%end%>
    </ul>
</p>
<%end%>

<% if @specials %>
<p>
  <strong>Specials:</strong><br/>
  <ul>
    <%@specials.each do |special|%>
      <% special.info.split(/[;]/).each do |s| %>
        <li><%= s %></li><br/>
      <% end %>
    <%end%>
    </ul>
</p>
<%end%>

<% if @recs %>
<p>
  <strong>Recommendations:</strong><br/>
  <ul>
    <%@recs.each do |rec|%>
      <% rec.info.split(/[;]/).each do |r| %>
        <li><%= r %></li><br/>
      <% end %>
    <%end%>
    </ul>
</p>
<%end%>

<p>
  <strong>Website:</strong><br/>
  <a href='<%= @transportation.website %>'><%= @transportation.website %>
</p>

<br/>
<%# <%= link_to 'Edit', edit_transportation_path(@transportation) %> 
<%= link_to "Food", foods_path %>
<%= link_to "Destinations", destinations_path %>
<%= link_to "Transportation", transportations_path%>
</br>
<%= link_to "Categories", categories_path %>
<%= link_to "Locations", locations_path %>