config/routes.rb
Rails.application.routes.draw do
  resources :transportations
  resources :locations
  resources :destinations
  resources :categories
  resources :foods

  root 'categories#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :food_categories
    has_many :foods, through: :food_categories
    has_many :dest_categories
    has_many :destinations, through: :dest_categories
    has_many :trans_categories
    has_many :transporations, through: :trans_categories

    validates :category, presence: true, uniqueness: true
end

app/models/dest_category.rb
class DestCategory < ApplicationRecord
    belongs_to :destination
    belongs_to :category

    validates :category_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_like.rb
class DestLike < ApplicationRecord
    belongs_to :destination
    belongs_to :like 

    validates :like_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_location.rb
class DestLocation < ApplicationRecord
    belongs_to :destination
    belongs_to :location 

    validates :location_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_note.rb
class DestNote < ApplicationRecord
    belongs_to :destination
    belongs_to :note

    validates :note_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_special.rb
class DestSpecial < ApplicationRecord
    belongs_to :destination
    belongs_to :special

    validates :special_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/destination.rb
class Destination < ApplicationRecord
    has_many :dest_categories
    has_many :dest_locations
    has_many :dest_notes
    has_many :dest_recommendations
    has_many :dest_specials
    has_many :dest_likes

    has_many :categories, through: :dest_categories
    has_many :locations, through: :dest_locations
    has_many :notes, through: :dest_notes
    has_many :recommendations, through: :dest_recommendations
    has_many :specials, through: :dest_specials
    has_many :likes, through: :dest_likes

    validates :name, presence: true, uniqueness: true
end

app/models/food.rb
class Food < ApplicationRecord
    has_many :food_categories
    has_many :food_locations
    has_many :food_notes
    has_many :food_recommendations
    has_many :food_specials
    has_many :food_likes

    has_many :categories, through: :food_categories
    has_many :locations, through: :food_locations
    has_many :notes, through: :food_notes
    has_many :recommendations, through: :food_recommendations
    has_many :specials, through: :food_specials
    has_many :likes, through: :food_likes

    validates :name, presence: true, uniqueness: true
end

app/models/food_category.rb
class FoodCategory < ApplicationRecord
    belongs_to :food
    belongs_to :category

    validates :category_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/food_like.rb
class FoodLike < ApplicationRecord
    belongs_to :food
    belongs_to :like

    validates :like_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/food_location.rb
class FoodLocation < ApplicationRecord
    belongs_to :food 
    belongs_to :location 

    validates :location_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/food_note.rb
class FoodNote < ApplicationRecord
    belongs_to :food 
    belongs_to :note 

    validates :note_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/food_special.rb
class FoodSpecial < ApplicationRecord
    belongs_to :food 
    belongs_to :special 

    validates :special_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/like.rb
class Like < ApplicationRecord
    has_many :food_likes
    has_many :foods, through: :food_likes
    has_many :dest_likes
    has_many :destinations, through: :dest_likes
    has_many :trans_likes
    has_many :transporations, through: :trans_likes

    validates :info, presence: true, uniqueness: true
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :food_locations
    has_many :foods, through: :food_locations
    has_many :dest_locations
    has_many :destinations, through: :dest_locations
    has_many :trans_locations
    has_many :transporations, through: :trans_locations

    validates :location, presence: true, uniqueness: true
end

app/models/note.rb
class Note < ApplicationRecord
    has_many :food_notes
    has_many :foods, through: :food_notes
    has_many :dest_notes
    has_many :destinations, through: :dest_notes
    has_many :trans_notes
    has_many :transporations, through: :trans_notes

    validates :info, presence: true, uniqueness: true
end

app/models/special.rb
class Special < ApplicationRecord
    has_many :food_specials
    has_many :foods, through: :food_specials
    has_many :dest_specials
    has_many :destinations, through: :dest_specials

    validates :info, presence: true, uniqueness: true
end

app/models/trans_like.rb
class TransLike < ApplicationRecord
    belongs_to :transportation 
    belongs_to :like

    validates :like_id, presence: true, uniqueness: { scope: :transportation_id }
end

app/models/trans_note.rb
class TransNote < ApplicationRecord
    belongs_to :transportation 
    belongs_to :note

    validates :note_id, presence: true, uniqueness: { scope: :transportation_id }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]

  # GET /foods or /foods.json
  def index
    @foods = Food.all.sort { |a, b| a[:name] <=> b[:name] }
  end

  # GET /foods/1 or /foods/1.json
  def show
    
    @foodspecials = FoodSpecial.where(food_id: params[:id]).to_a
    
    if @foodspecials != []
      @specials = []
      @foodspecials.each do |s|
        @specials.push(Special.find_by(:id => s[:special_id]))
      end
    end

    
    @foodnotes = FoodNote.where(food_id: params[:id]).to_a
    
    if @foodnotes != []
      @notes = []
      @foodnotes.each do |n|
        @notes.push(Note.find_by(:id => n[:note_id]))
      end
    end

    
    @foodrecs = FoodRecommendation.where(:food_id => params[:id]).to_a
    
    if @foodrecs != []
      @recs = []
      @foodrecs.each do |r|
        @recs.push(Recommendation.find_by(:id => r[:recommendation_id]))
      end
    end


    @foodlocs = FoodLocation.where(food_id: params[:id]).to_a
    
    if @foodlocs != []
      @locs = []
      @foodlocs.each do |l|
        @locs.push(Location.find_by(:id => l[:location_id]))
      end
    end
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: "Food was successfully created." }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: "Food was successfully updated." }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :hours, :website)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.text_field :hours %>
  </div>

  <div class="field">
    <%= form.label :ARRAY %>
    <%= form.text_field :ARRAY %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food</h1>

<table>
  <thead>
    <tr>
      <th class='name'>Name</th>
      <th class='hours'>Hours</th>
      <th class='web'>Website</th>
      
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td class='name'><%= link_to food.name, food %></td>
        <td class='hours'><% food.hours.split(',').each do |hour|%>
              <%= hour %></br>
            <% end %></td>
        <td class='web'><a href='<%= food.website %>'><%= food.website %></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br/>


<%= link_to "Destinations", destinations_path %>
<%= link_to "Transportation", transportations_path%>
</br>
<%= link_to "Categories", categories_path %>
<%= link_to "Locations", locations_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  
  <%= @food.name %>
</h2>
<% @locs.each do |loc| %>
  <h4>@ <%= loc.location %></h4>
<% end %>
</br>
<p>
  <strong>Hours:</strong>
  <br/>
  <ul>
  <%@food.hours.split(/[,]/).each do |hour|%>
    <li><%= hour %></li><br/>
  <%end%>
  </ul>
</p>

<% if @notes %>
<p>
  <strong>Notes:</strong><br/>
  <ul>
    <%@notes.each do |note|%>
      <% note.info.split(/[;]/).each do |n| %>
        <li><%= n %></li><br/>
      <% end %>
    <%end%>
    </ul>
</p>
<%end%>

<% if @specials %>
<p>
  <strong>Specials:</strong><br/>
  <ul>
    <%@specials.each do |special|%>
      <% special.info.split(/[;]/).each do |s| %>
        <li><%= s %></li><br/>
      <% end %>
    <%end%>
    </ul>
</p>
<%end%>

<% if @recs %>

<p>
  <strong>Recommendations:</strong><br/>
  <ul>
    <%@recs.each do |rec|%>
      <% rec.info.split(/[;]/).each do |r| %>
        <li><%= r %></li><br/>
      <% end %>
    <%end%>
    </ul>
</p>
<%end%>

<p>
  <strong>Website:</strong><br/>
  <a href='<%= @food.website %>'><%= @food.website %>
</p>
<br/>

<%# <%= link_to 'Edit', edit_food_path(@food) %> 

<%= link_to "Food", foods_path %>
<%= link_to "Destinations", destinations_path %>
<%= link_to "Transportation", transportations_path%>
</br>
<%= link_to "Categories", categories_path %>
<%= link_to "Locations", locations_path %>