config/routes.rb
Rails.application.routes.draw do
  resources :transportations
  resources :locations
  resources :destinations
  resources :categories
  resources :foods

  root 'categories#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :food_categories
    has_many :foods, through: :food_categories
    has_many :dest_categories
    has_many :destinations, through: :dest_categories
    has_many :trans_categories
    has_many :transporations, through: :trans_categories

    validates :category, presence: true, uniqueness: true
end

app/models/dest_category.rb
class DestCategory < ApplicationRecord
    belongs_to :destination
    belongs_to :category

    validates :category_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_like.rb
class DestLike < ApplicationRecord
    belongs_to :destination
    belongs_to :like 

    validates :like_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_location.rb
class DestLocation < ApplicationRecord
    belongs_to :destination
    belongs_to :location 

    validates :location_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_note.rb
class DestNote < ApplicationRecord
    belongs_to :destination
    belongs_to :note

    validates :note_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/dest_special.rb
class DestSpecial < ApplicationRecord
    belongs_to :destination
    belongs_to :special

    validates :special_id, presence: true, uniqueness: { scope: :destination_id }
end

app/models/destination.rb
class Destination < ApplicationRecord
    has_many :dest_categories
    has_many :dest_locations
    has_many :dest_notes
    has_many :dest_recommendations
    has_many :dest_specials
    has_many :dest_likes

    has_many :categories, through: :dest_categories
    has_many :locations, through: :dest_locations
    has_many :notes, through: :dest_notes
    has_many :recommendations, through: :dest_recommendations
    has_many :specials, through: :dest_specials
    has_many :likes, through: :dest_likes

    validates :name, presence: true, uniqueness: true
end

app/models/food.rb
class Food < ApplicationRecord
    has_many :food_categories
    has_many :food_locations
    has_many :food_notes
    has_many :food_recommendations
    has_many :food_specials
    has_many :food_likes

    has_many :categories, through: :food_categories
    has_many :locations, through: :food_locations
    has_many :notes, through: :food_notes
    has_many :recommendations, through: :food_recommendations
    has_many :specials, through: :food_specials
    has_many :likes, through: :food_likes

    validates :name, presence: true, uniqueness: true
end

app/models/food_category.rb
class FoodCategory < ApplicationRecord
    belongs_to :food
    belongs_to :category

    validates :category_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/food_like.rb
class FoodLike < ApplicationRecord
    belongs_to :food
    belongs_to :like

    validates :like_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/food_note.rb
class FoodNote < ApplicationRecord
    belongs_to :food 
    belongs_to :note 

    validates :note_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/food_special.rb
class FoodSpecial < ApplicationRecord
    belongs_to :food 
    belongs_to :special 

    validates :special_id, presence: true, uniqueness: { scope: :food_id }
end

app/models/like.rb
class Like < ApplicationRecord
    has_many :food_likes
    has_many :foods, through: :food_likes
    has_many :dest_likes
    has_many :destinations, through: :dest_likes
    has_many :trans_likes
    has_many :transporations, through: :trans_likes

    validates :info, presence: true, uniqueness: true
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :food_locations
    has_many :foods, through: :food_locations
    has_many :dest_locations
    has_many :destinations, through: :dest_locations
    has_many :trans_locations
    has_many :transporations, through: :trans_locations

    validates :location, presence: true, uniqueness: true
end

app/models/note.rb
class Note < ApplicationRecord
    has_many :food_notes
    has_many :foods, through: :food_notes
    has_many :dest_notes
    has_many :destinations, through: :dest_notes
    has_many :trans_notes
    has_many :transporations, through: :trans_notes

    validates :info, presence: true, uniqueness: true
end

app/models/special.rb
class Special < ApplicationRecord
    has_many :food_specials
    has_many :foods, through: :food_specials
    has_many :dest_specials
    has_many :destinations, through: :dest_specials

    validates :info, presence: true, uniqueness: true
end

app/models/trans_like.rb
class TransLike < ApplicationRecord
    belongs_to :transportation 
    belongs_to :like

    validates :like_id, presence: true, uniqueness: { scope: :transportation_id }
end

app/models/trans_note.rb
class TransNote < ApplicationRecord
    belongs_to :transportation 
    belongs_to :note

    validates :note_id, presence: true, uniqueness: { scope: :transportation_id }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all.sort { |a, b| a[:category] <=> b[:category] }
  end

  # GET /categories/1 or /categories/1.json
  def show
    @foodcats = FoodCategory.where(category_id: params[:id]).to_a
    
    if @foodcats != []
      @foods = []
      @foodcats.each do |f|
        @foods.push(Food.find_by(:id => f[:food_id]))
      end
      @foods = @foods.sort_by { |item| item.name }
    end

    @destcats = DestCategory.where(category_id: params[:id]).to_a
    
    if @destcats != []
      @dests = []
      @destcats.each do |d|
        @dests.push(Destination.find_by(:id => d[:destination_id]))
      end
      @dests = @dests.sort_by { |item| item.name }
    end

    @loccats = TransCategory.where(category_id: params[:id]).to_a
    
    if @loccats != []
      @locs = []
      @loccats.each do |l|
        @locs.push(Transportation.find_by(:id => l[:transportation_id]))
      end
      @locs = @locs.sort_by { |item| item.name }
    end

  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    # respond_to do |format|
    #   if @category.save
    #     format.html { redirect_to @category, notice: "Category was successfully created." }
    #     format.json { render :show, status: :created, location: @category }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @category.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<ul>
  

  
    <% @categories.each do |category| %>
      
        <li><%= link_to category.category, category %></li></br>
        
        
      
    <% end %>
  
</table>

<%= link_to "Food", foods_path %>
<%= link_to "Destinations", destinations_path %>
<%= link_to "Transportation", transportations_path%>
</br>
<%= link_to "Locations", locations_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h3><strong><%= @category.category %></strong></h3>
  <%if @foods %>
  </br>
  <b><em>Foods:</em></b>
  <ul>
      <% @foods.each do |food| %>
        <li><%= link_to food.name, food_path(food.id) %></li></br>
      <% end %>
  </ul>
  <% end %>

<% if @dests %>
  </br>
  <b><em>Destinations:</em></b>
  <ul>
      <% @dests.each do |dest| %>
        <li><%= link_to dest.name, destination_path(dest.id) %></li></br>
      <% end %>
  </ul>
  <% end %>

<% if @locs %>
  </br>
  <b><em>Transportation:</em></b>
  <ul>
      <% @locs.each do |loc| %>
        <li><%= link_to loc.name, transportation_path(loc.id) %></li></br>
      <% end %>
  </ul>
  <% end %>
</p>


<%= link_to "Food", foods_path %>
<%= link_to "Destinations", destinations_path %>
<%= link_to "Transportation", transportations_path%>
</br>
<%= link_to "Categories", categories_path %>
<%= link_to "Locations", locations_path %>